class TableNamesEnum:
    def __init__(self):
        self.PERSON = "person"
        self.PLACE = "place"
        self.THING = "thing"
        self.ROLE = "role"
        self.EVENT = "event"
        self.ACTION = "action"
        self.ACTION_ACTION = "action_action"
        self.ACTION_EVENT = "action_event"
        self.ACTION_PLACE = "action_place"
        self.EVENT_EVENT = "action_event"
        self.EVENT_PLACE = "action_place"
        self.PERSON_ACTION = "person_action"
        self.PERSON_EVENT = "person_event"
        self.PERSON_PERSON = "person_person"
        self.PERSON_PLACE = "person_place"
        self.PERSON_THING = "person_thing"
        self.PERSON_ROLE = "person_role"
        self.PLACE_PLACE = "place_place"
        self.THING_ACTION = "thing_action"
        self.THING_EVENT = "thing_event"
        self.THING_PLACE = "thing_place"
        self.THING_THING = "thing_thing"
        self.RELATIONSHIP_TYPE = "relationship_type"


class ColumnNamesEnum:
    def __init__(self):
        self.ID = "id"
        self.SHORT_DESCRIPTION = "short_description"
        self.LONG_DESCRIPTION = "long_description"
        self.DESCRIPTION = "description"
        self.START_DATE = "start_date"
        self.START_TIME = "start_time"
        self.END_DATE = "end_date"
        self.END_TIME = "end_time"
        self.FIRST_NAME = "first_name"
        self.MIDDLE_NAME = "middle_name"
        self.LAST_NAME = "last_name"
        self.PREFIX_NAME = "prefix_name"
        self.SUFFIX_NAME = "suffix_name"
        self.PHONE_NUMBER = "phone_number"
        self.STREET = "street"
        self.STREET2 = "street2"
        self.CITY = "city"
        self.STATE = "state"
        self.ZIP_CODE = "zip_code"
        self.PERSON_ID = "person_id"
        self.PLACE_ID = "place_id"
        self.THING_ID = "thing_id"
        self.ROLE_ID = "role_id"
        self.EVENT_ID = "event_id"
        self.ACTION_ID = "action_id"
        self.ACTION_ID_A = "action_id_a"
        self.ACTION_ID_B = "action_id_b"
        self.EVENT_ID_A = "event_id_a"
        self.EVENT_ID_B = "event_id_b"
        self.PERSON_ID_A = "person_id_a"
        self.PERSON_ID_B = "person_id_b"
        self.PLACE_ID_A = "place_id_a"
        self.PLACE_ID_B = "place_id_b"
        self.THING_ID_A = "thing_id_a"
        self.THING_ID_B = "thing_id_b"
        self.RELATIONSHIP_TYPE_ID = "relationship_type_id"


